name: blap_main_website_desktop
description: Slogan please

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^3.0.10
  google_fonts: 1.1.2
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true